site_name: systems-behavior-lab
site_description: Experiments investigating why systems behave the way they do
repo_url: https://github.com/jsleeair/systems-behavior-lab
repo_name: jsleeair/systems-behavior-lab

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - content.code.copy
    - toc.integrate

nav:
  - Home: index.md
  - Labs:
        - 00 Build & Binary:
                - 00 Translation Unit: 00-build-and-binary/00-translation-unit.md
        - 01 Symbol Resolution:
                - 00 ELF Symbol Table: 01-symbol-resolution/00-elf-symbol-table.md
  - About: about.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
